### ISSUE TITLE
Validation Select tag does not work

### ISSUE THREAD

**Issue by sakhnov** [AdrianVillamayor/Wizard-JS#14]
When connecting wizard.min.js
Select validation does not work; in the wizard.min.js file it is missing in the switch block:

                    case "SELECT":
                        check = $_.checkSelect(e);
                        break;
![image](https://github.com/user-attachments/assets/0c92b23c-52c3-4890-9949-0c959b0a00e4)

**Comment by AdrianVillamayor** [comment]
Hi @sakhnov ,

I've improved the validation for select elements by updating the compression system. This ensures that validation logic is applied correctly, preventing errors during form submission. I also added new security layers using esLint and Webpack, which help ensure that our builds remain secure and high-quality.


You have it all documented in the [Readme.me](https://github.com/AdrianVillamayor/Wizard-JS/blob/main/README.md) and in the [Changelog](https://github.com/AdrianVillamayor/Wizard-JS/compare/v1.9.9...v2.0.3).

I hope I solved your problem, anything else let me know.

Thank you very much for your help 🙌🏻.
