### ISSUE TITLE
Button configuration not hide the finish button

### ISSUE THREAD

**Issue by aalfiann** [AdrianVillamayor/Wizard-JS#4]
**Describe the bug**
When I set configuration button to false, the prev and next button was hidden, but the finish button is not hiding.

**To Reproduce**
1. set the configuration like this
```js
let args = {
      "wz_class": wz_class,
      "wz_nav_style": "progress", // dots, tabs, progress
      "wz_ori" : "vertical",
      "buttons": false,
      "navigation": 'all' // buttons, nav, all
  };
```
2. Done, the prev and next button is hiding, but the finish button won't hide.

**Desktop :**
 - OS: Elementary OS
 - Browser Firefox Mozilla
 - Version 107.0.1 (64bit)

**Comment by AdrianVillamayor** [comment]
Hi @aleaforny ,

Now if you add the option buttons:false, all buttons will be hidden, including Submit/Finish.

In addition, a couple of visual enhancements have been added to make the usable navigations stand out more.

You have all the changes [here](https://github.com/AdrianVillamayor/Wizard-JS/compare/v1.9...v1.9.1).

I hope I solved your problem, anything else let me know.

Thank you very much for your help 🙌🏻.
