### ISSUE TITLE
How to listen the navigation change?

### ISSUE THREAD

**Issue by aalfiann** [AdrianVillamayor/Wizard-JS#5]
I didn't found how to listen the event when navigation changed?

Thanks for the help

**Comment by AdrianVillamayor** [comment]
Hi @aalfiann ,

Actually you cannot dynamically change the navigation of the wizard. For that you should destroy it and create it with a new configuration.

Could you give me an example of the use you need?  

Thanks in advance for your feedback

**Comment by aalfiann** [comment]
I mean, I just want to listen when someone change the step wizard through navigation..

**Comment by AdrianVillamayor** [comment]
Hi @aalfiann ,

Sorry for the time lapse between responses.

Two events have been added for when you navigate with the nabar.

- forwardNavWizard
- backwardNavWizard

You have it all documented in the [Readme.me](https://github.com/AdrianVillamayor/Wizard-JS/blob/main/README.md) and in the [Changelog](https://github.com/AdrianVillamayor/Wizard-JS/compare/v1.8...v1.9).

I hope I solved your problem, anything else let me know.

Thank you very much for your help 🙌🏻.
