### ISSUE TITLE
Dynamic Steps

### ISSUE THREAD

**Issue by amdemas** [AdrianVillamayor/Wizard-JS#8]
**Is your feature request related to a problem? Please describe.**
I have a wizard form that asks an individual various questions. Based on the response, I would like to append additional steps. 

**Describe the solution you'd like**
Ability to dynamically add steps through a registration method and then invoke init() (or not).

**Comment by AdrianVillamayor** [comment]
Hii @amdemas ,

I am working on it, at the end of this week or early next week I will upload a version with your request.

Thank you very much for your help 🙌🏻.

**Comment by AdrianVillamayor** [comment]
Hi @amdemas ,

Sorry for the time lapse between replies.

I just uploaded a new version, [1.9.6](https://github.com/AdrianVillamayor/Wizard-JS/releases/tag/v1.9.6), in it goes the update() method. It allows you to update the state of the wizard without having to destroy it.

Here is an example of how it would work.

```javascript
function setStep(wizard) {
    $html = `<div class="card card-body m-4 wizard-step" data-id="patata" data-title="Adrii"> <label class="question"> Embedded step </label> <input type="text" maxlength="100" name="patata" class="form-control required" placeholder="Embedded step"> </div>`;

    const wz = document.querySelector(wizard.wz_class);
    const wz_content = wz.querySelector(wizard.wz_content);

    let target = wz_content.querySelector(`${wizard.wz_step}[data-step="8"]`)

    target.insertAdjacentHTML('beforebegin', $html);

    wizard.update();
}
```

You have it all documented in the [Readme.me](https://github.com/AdrianVillamayor/Wizard-JS/blob/main/README.md) and in the [Changelog](https://github.com/AdrianVillamayor/Wizard-JS/compare/v1.9.3...v1.9.6).

I hope I solved your problem, anything else let me know.

Thank you very much for your help 🙌🏻.

**Comment by amdemas** [comment]
Perfect! Thank you @AdrianVillamayor
