### ISSUE TITLE
Validation not working on select elements

### ISSUE THREAD

**Issue by sal3hkarimi** [AdrianVillamayor/Wizard-JS#9]
Thank you for the library you made.
I used this library and ran into a problem, which is that validation doesn't work on select elements.
How can I do this manually because I have a dropzone and I want to apply a validation operation on it?
Thanks a lot!

**Comment by AdrianVillamayor** [comment]
Hii @silentcode-ir ,

Could you show me an example of the code, to validate where it is failing ?

Thank you very much for your help 🙌🏻.

**Comment by sal3hkarimi** [comment]
I updated the desired packages and it was fixed. Thank you for your very good library.
